version: 2
project_name: sshm

before:
  hooks:
  - go mod tidy
  - go test ./...

builds:
- id: sshm
  main: ./main.go
  binary: sshm
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  - "386"
  - arm
  goarm:
  - "6"
  - "7"
  ignore:
  # Skip ARM for Windows (not commonly used)
  - goos: windows
    goarch: arm
  - goos: windows
    goarch: arm64
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w
  - -X github.com/Gu1llaum-3/sshm/cmd.AppVersion={{.Version}}
  flags:
  - -trimpath

archives:
- id: sshm
  formats: [ "tar.gz" ]
  # Use zip for Windows
  format_overrides:
  - goos: windows
    formats: [ "zip" ]
  # Template for archive name
  name_template: >-
    {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
  files:
  - LICENSE
  - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "^ci:"
    - "^chore:"
    - "^build:"
  groups:
  - title: Features
    regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    order: 0
  - title: Bug fixes
    regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    order: 1
  - title: Others
    order: 999

# Homebrew tap configuration (Formula pour CLI)
brews:
- name: sshm
  repository:
    owner: Gu1llaum-3
    name: homebrew-sshm
    # Token with repo permissions for your homebrew-sshm repo
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com
  commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://github.com/Gu1llaum-3/sshm"
  description: "A modern SSH connection manager for your terminal"
  license: MIT
  skip_upload: auto
  # Test command to verify installation
  test: |
    system "#{bin}/sshm --version"

# Release configuration
release:
  github:
    owner: Gu1llaum-3
    name: sshm
  prerelease: auto
  draft: false
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## SSHM {{.Version}}

    Thank you for downloading SSHM! 

    ### Installation

    **Homebrew (macOS/Linux):**
    ```bash
    brew tap Gu1llaum-3/sshm
    brew install sshm
    ```

    **Manual Installation:**
    Download the appropriate binary for your platform from the assets below.

  footer: |
    ## Full Changelog

    See all changes at https://github.com/Gu1llaum-3/sshm/compare/{{.PreviousTag}}...{{.Tag}}

    ---

    Released with ❤️ by [GoReleaser](https://github.com/goreleaser/goreleaser)

# Snapshot builds (for non-tag builds)
snapshot:
  version_template: "{{ .Tag }}-snapshot-{{.ShortCommit}}"

# Metadata for package managers
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
